spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sql_lims?serverTimezone=UTC
    username: 'root'
    password: '0000'
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
#  security:
#    user:
#      name: 'admin'
#      password: '0000'
mybatis-plus:
  mapperLocations: classpath:mybatis/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-aliases-package: org.honma.*.entity.**